const authRouter = require('./auth')
const productRouter = require('./product')
const warehouseRouter = require('./warehouses')
const clientRouter = require('./client')
const dashRouter = require('./dashboard')
const purchaseRouter = require('./purchase')
const orderRouter = require('./order')
const saleRouter = require('./sale')
const supplierRouter = require('./supplier')
module.exports = function (app) {
    app.use('/api/auth', authRouter)
    app.use('/api/product', productRouter)
    app.use('/api/warehouse', warehouseRouter)
    app.use('/api/client', clientRouter)
    app.use('/api/dashboard', dashRouter)
    app.use('/api/order',orderRouter)  
    app.use('/api/supplier',supplierRouter)
    app.use('/api/sale',saleRouter)
    app.use('/api/purchase', purchaseRouter)

}