module.exports = {
    USER_ALREADY_EXIST: 'USER_ALREADY_EXIST',
    SERVER_ERROR: 'SERVER_ERROR',
    INVALID_CREDITS: 'INVALID_CREDITS',
    SUCCESSFULY_DELETED: 'SUCCESSFULY_DELETED',
    DOES_NOT_EXIST: 'DOES_NOT_EXIST',
    SAME_USERNAME_ALREADY_EXISTS: 'SAME_USERNAME_ALREADY_EXISTS',
    SAME_PHONENUMBER_ALREADY_EXISTS: 'SAME_PHONENUMBER_ALREADY_EXISTS',
    CLIENT_DOES_NOT_EXIST: 'CLIENT_DOES_NOT_EXIST',
    SERVER_ERROR_SEARCH: 'SERVER_ERROR_SEARCH',
    PRODUCT_ALREADY_EXIST: 'PRODUCT_ALREADY_EXIST',
    NOT_ENOUGH_STOCK: 'NOT_ENOUGH_STOCK',
    PRODUCT_NOT_EXISTENT: 'PRODUCT_NOT_EXISTENT',
    WAREHOUSE_NON_EXISTENT: 'WAREHOUSE_NON_EXISTENT',
    WAREHOUSE_ALREADY_EXIST: 'WAREHOUSE_ALREADY_EXIST',
    WAREHOUSE_DOES_NOT_EXIST: 'WAREHOUSE_DOES_NOT_EXIST'
}